name: Sync to Staging Workflow

on:
  push:
    tags:
      - 'sync-to-staging'
  create:
    tags:
      - 'sync-to-staging'

jobs:
  sync-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: echo "Hello World"
