name: Sync to Staging Label Workflow

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  sync-to-staging:
    if: |
      (github.event.label.name == 'sync-to-staging') ||
      (contains(github.event.pull_request.labels.*.name, 'sync-to-staging') && github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello World
        run: echo "Hello World"
